### ISSUE TITLE
Short installation instructions?

### ISSUE THREAD

**Issue by rubyFeedback** [smallwat3r/droid-sans-mono-sw#2]
Hello Matthieu,

Would you think it may be possible to add a short installation instruction entry at the main README? Does not have to be long, just some starters to refresh people's memory so they don't have to look it up elsewhere. Please disregard if this is considered unwanted or unnecessary. Thanks!

**Comment by smallwat3r** [comment]
Hi @rubyFeedback 
That's actually a good point, thanks for the feedback. 
I've added some installation instructions in the README.
But I think in most OS you can right-click on the .ttf file and click install.
